production:
  adapter: postgresql
  encoding: unicode
  database: rails_mister_cocktail_production
  pool: 5
  username: alinakabirova
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: rails_mister_cocktail_dev
  pool: 5
  username: alinakabirova
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_mister_cocktail_test
  pool: 5
  username: alinakabirova
  password:
